### ISSUE TITLE
Issue | Paper auto-replenish loot problem

### ISSUE THREAD

**Issue by knniDE** [fantahund/FancyFirework#3]
If you use the "auto-replenish" option in paperspigot, then fancyfirework seems to have a problem with it. The loot of the crate is refilled depending on the settings in Paper. However, the fireworks regenerate every time you open the chest.

fancyfirework loottable config:
```yml
loottable:
  enabled: true
  chance: 0.5
  wanderingtrader:
    enabled: false
    chance: 0.3
    minprice: 8
    maxprice: 32
    maxuse: 4
```

paperspigot  paper-world-default loottable config
```yml
lootables:
  auto-replenish: true
  max-refills: -1
  refresh-max: 4d
  refresh-min: 12h
  reset-seed-on-fill: true
  restrict-player-reloot: true
```

video:
https://github.com/fantahund/FancyFirework/assets/18620563/8e0cf4a6-0052-4f3a-846e-cd3fa62c8ba6

hope you can fix this somehow
